# cloudbuild.yaml
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/anchor-score-api', '.']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/anchor-score-api']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - anchor-score-api
      - --image
      - gcr.io/$PROJECT_ID/anchor-score-api
      - --platform
      - managed
      - --region
      - us-central1
      - --allow-unauthenticated

